syncfusion-content/ej2-charts-docs

ej2-javascript/stock-chart/ej2-javascript-stock-chart-toc.html
=> documentation(EJ2-71942): Fixed toc issues

ej2-javascript/code-snippet/rangenavigator/getting-started-cs11/index.js, ej2-javascript/code-snippet/rangenavigator/getting-started-cs11/js/index.html
=> Documentation(835054): Changed HTML file

ej2-javascript/code-snippet/chart/chart-types-cs24/index.js, ej2-javascript/code-snippet/rangenavigator/axis-cs18/js/index.html
=> (EJ2-834303): Name changes.

ej2-javascript/code-snippet/chart/chart-types-cs24/index.js, ej2-javascript/code-snippet/rangenavigator/axis-cs18/js/index.html
=> (EJ2-836705): Preview issue.

ej2-javascript/range-navigator/ej1-api-migration.md
=> (EJ2-845675): Resolved the error.

ej2-javascript/range-navigator/ej1-api-migration.md
Need to resolve resolved UG publishing failures.
We have not verified syntax and tags that are closed properly.
Find how it was missed in our earlier testing and development by analyzing the below checklist. This will help prevent similar mistakes in the future. 
- Specification document
- Requirement document
- Common guidelines / Core team guideline
- Specification document
- Requirement document
We have not checked and ensured locally for the syntax and tags that are placed properly.
Verified the syntax were placed properly and Tags were created and closed properly on the document.
Need to ensure the visual content of the Documentation. 
No
We have fixed this issue via adjusting the syntax and tag content of the document that are placed properly.
Ensured the EJ2 Vue documentation.
- …
=> bug(849798): Need to resolve resolved UG publishing failures

ej2-javascript/code-snippet/stock-chart/getting-started-cs38/index.js, ej2-javascript/code-snippet/stock-chart/getting-started-cs38/index.ts
Fixed the preview issue in DateTimeCategory Axis sample.
=> (EJ2-848281): To fixed the preview issue.

ej2-javascript/chart/synchronized-chart.md
Added api for Synchronized Chart in TS & JS UG.
=> (EJ2-848281): Added api for Synchronized Chart.

ej2-javascript/accumulation-chart/js/es5-getting-started.md, ej2-javascript/bullet-chart/js/es5-getting-started.md, ej2-javascript/chart/js/es5-getting-started.md, ej2-javascript/range-navigator/js/es5-getting-started.md, ej2-javascript/stock-chart/js/es5-getting-started.md
fixed getting the started issue in chart
=> bug(EJ2-853445) - fixed getting the started issue in chart

ej2-javascript/accumulation-chart/js/es5-getting-started.md, ej2-javascript/bullet-chart/js/es5-getting-started.md, ej2-javascript/chart/js/es5-getting-started.md, ej2-javascript/range-navigator/js/es5-getting-started.md, ej2-javascript/stock-chart/js/es5-getting-started.md
fixed getting the started issue in chart hotfix
=> bug(EJ2-853445) - fixed getting the started issue in chart hotfix

ej2-javascript/3D chart/ts/getting-started.md
Content and sample corrections in 3D Chart sample.
=> (EJ2-859817): Content and sample corrections in 3D Chart UG.

ej2-javascript/accumulation-chart/tool-tip.md, ej2-javascript/chart/Chart-types/range-step-area.md, ej2-javascript/chart/Chart-types/stacked-step-area.md, ej2-javascript/chart/Chart-types/step-area.md, ej2-javascript/chart/Chart-types/step-line.md, ej2-javascript/chart/tool-tip.md
Added api for for vol4 features sample used guide in TypeScript and JavaScript.
=> (EJ2-861407): Added api for vol4 features samples.

ej2-javascript/3D-chart/js/es5-getting-started.md, ej2-javascript/3D-chart/ts/getting-started.md
Added api for 3D Chart TS and JS documentation.
=> (EJ2-861407): Added api to 3D Chart documentation in TS and JS.

ej2-javascript/3D-chart/js/es5-getting-started.md, ej2-javascript/3D-chart/ts/getting-started.md
Added api for 3D Chart TS and JS documentation.
=> (EJ2-862259): Added api to 3D Chart documentation in TS and JS.

ej2-javascript/chart/how-to/selected-data-grid.md, ej2-javascript/code-snippet/chart/grid-visual-cs2/js/index.html, ej2-javascript/code-snippet/chart/grid-visual-cs2/systemjs.config.js, ej2-javascript/code-snippet/chart/grid-visual-cs2/ts/index.html, ej2-javascript/code-snippet/chart/grid-visual-cs3/js/index.html, ej2-javascript/code-snippet/chart/grid-visual-cs3/systemjs.config.js, ej2-javascript/code-snippet/chart/grid-visual-cs3/ts/index.html, ej2-javascript/code-snippet/chart/how-to-cs16/js/index.html, ej2-javascript/code-snippet/chart/how-to-cs16/systemjs.config.js, ej2-javascript/code-snippet/chart/how-to-cs16/ts/index.html, ej2-javascript/code-snippet/chart/how-to-cs4/systemjs.config.js, ej2-javascript/code-snippet/chart3d/getting-started-cs1/systemjs.config.js, ej2-javascript/code-snippet/chart3d/getting-started-cs2/systemjs.config.js, ej2-javascript/code-snippet/chart3d/getting-started-cs3/systemjs.config.js, ej2-javascript/code-snippet/chart3d/getting-started-cs4/systemjs.config.js, ej2-javascript/code-snippet/chart3d/getting-started-cs5/systemjs.config.js, ej2-javascript/code-snippet/chart3d/getting-started-cs6/systemjs.config.js, ej2-javascript/code-snippet/chart3d/getting-started-cs7/systemjs.config.js
Added dependencies in TS and JS 3D Chart documentation.
=> (EJ2-861407): Added dependencies in 3D Chart documentation in TS and JS.

ej2-javascript/chart/how-to/selected-data-grid.md, ej2-javascript/code-snippet/chart/grid-visual-cs2/js/index.html, ej2-javascript/code-snippet/chart/grid-visual-cs2/systemjs.config.js, ej2-javascript/code-snippet/chart/grid-visual-cs2/ts/index.html, ej2-javascript/code-snippet/chart/grid-visual-cs3/js/index.html, ej2-javascript/code-snippet/chart/grid-visual-cs3/systemjs.config.js, ej2-javascript/code-snippet/chart/grid-visual-cs3/ts/index.html, ej2-javascript/code-snippet/chart/how-to-cs16/js/index.html, ej2-javascript/code-snippet/chart/how-to-cs16/systemjs.config.js, ej2-javascript/code-snippet/chart/how-to-cs16/ts/index.html, ej2-javascript/code-snippet/chart/how-to-cs4/systemjs.config.js, ej2-javascript/code-snippet/chart3d/getting-started-cs1/systemjs.config.js, ej2-javascript/code-snippet/chart3d/getting-started-cs2/systemjs.config.js, ej2-javascript/code-snippet/chart3d/getting-started-cs3/systemjs.config.js, ej2-javascript/code-snippet/chart3d/getting-started-cs4/systemjs.config.js, ej2-javascript/code-snippet/chart3d/getting-started-cs5/systemjs.config.js, ej2-javascript/code-snippet/chart3d/getting-started-cs6/systemjs.config.js, ej2-javascript/code-snippet/chart3d/getting-started-cs7/systemjs.config.js
Added dependencies in TS and JS 3D Chart documentation.
=> (EJ2-862259): Added dependencies in 3D Chart documentation in TS and JS.

ej2-javascript/accumulation-chart/accessibility.md, ej2-javascript/bullet-chart/accessibility.md, ej2-javascript/chart/accessibility.md, ej2-javascript/range-navigator/accessibility.md, ej2-javascript/stock-chart/accessibility.md
Accessibility sample changes included in TS and JS documentation.
=> (EJ2-861407): Changes included into the Accessibility sample.

ej2-javascript/accumulation-chart/accessibility.md, ej2-javascript/bullet-chart/accessibility.md, ej2-javascript/chart/accessibility.md, ej2-javascript/range-navigator/accessibility.md, ej2-javascript/stock-chart/accessibility.md
Accessibility sample changes included in TS and JS documentation.
=> (EJ2-862259): Changes included into the Accessibility sample.

ej2-javascript/accumulation-chart/accessibility.md, ej2-javascript/accumulation-chart/ej2-javascript-accumulation-chart-toc.html, ej2-javascript/accumulation-chart/ej2-typescript-accumulation-chart-toc.html, ej2-javascript/bullet-chart/accessibility.md, ej2-javascript/bullet-chart/ej2-javascript-bullet-chart-toc.html, ej2-javascript/bullet-chart/ej2-typescript-bullet-chart-toc.html, ej2-javascript/chart/accessibility.md, ej2-javascript/range-navigator/accessibility.md, ej2-javascript/range-navigator/ej2-javascript-range-navigator-toc.html, ej2-javascript/range-navigator/ej2-typescript-range-navigator-toc.html, ej2-javascript/stock-chart/accessibility.md, ej2-javascript/stock-chart/ej2-javascript-stock-chart-toc.html, ej2-javascript/stock-chart/ej2-typescript-stock-chart-toc.html
Changes included in accessibility sample.
=> (EJ2-861407): Changes included in accessibility sample.

ej2-javascript/accumulation-chart/accessibility.md, ej2-javascript/accumulation-chart/ej2-javascript-accumulation-chart-toc.html, ej2-javascript/accumulation-chart/ej2-typescript-accumulation-chart-toc.html, ej2-javascript/bullet-chart/accessibility.md, ej2-javascript/bullet-chart/ej2-javascript-bullet-chart-toc.html, ej2-javascript/bullet-chart/ej2-typescript-bullet-chart-toc.html, ej2-javascript/chart/accessibility.md, ej2-javascript/range-navigator/accessibility.md, ej2-javascript/range-navigator/ej2-javascript-range-navigator-toc.html, ej2-javascript/range-navigator/ej2-typescript-range-navigator-toc.html, ej2-javascript/stock-chart/accessibility.md, ej2-javascript/stock-chart/ej2-javascript-stock-chart-toc.html, ej2-javascript/stock-chart/ej2-typescript-stock-chart-toc.html
Changes included in accessibility sample.
=> (EJ2-862259): Changes included in accessibility sample.

ej2-javascript/accumulation-chart/accessibility.md, ej2-javascript/bullet-chart/accessibility.md, ej2-javascript/chart/accessibility.md, ej2-javascript/range-navigator/accessibility.md, ej2-javascript/stock-chart/accessibility.md
Need to modified the icons on accessibility document. The Icons are newly created for the compilance measuring.
[866555](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/866555)
NA
Feature matrix document updated against this feature and committed in this [common location] (https://syncfusion.sharepoint.com/sites/EJ2ProductOwners/Shared%20Documents/Forms/AllItems.aspx?viewid=ae81c682%2D3d0f%2D462a%2Db8ec%2D7358748d489d&id=%2Fsites%2FEJ2ProductOwners%2FShared%20Documents%2FGeneral%2FFeature%20Matrix%20%2D%20Documents) . 
Provide the details about the areas or combinations which have been tested against this code changes.
NA
Mark 'Is Automated' field as (Yes, Manual, Not Applicable) in corresponding JIRA task once the feature is automated. 
NA
UX changes got approval if UI is …
=> 866555: Need to modified the icons on accessibility document

ej2-javascript/accumulation-chart/accessibility.md, ej2-javascript/bullet-chart/accessibility.md, ej2-javascript/chart/accessibility.md, ej2-javascript/chart/chart-print.md, ej2-javascript/code-snippet/chart/export-cs6/index.ts, ej2-javascript/range-navigator/accessibility.md, ej2-javascript/stock-chart/accessibility.md
=> 866684: Resolved the conflict in accessibility sample.

ej2-javascript/chart/Chart-types/stack-area.md
Hello,
I have worked on links with redirects,
Regards,
Beryl
=> SEO-179239-Redirect-Links-TS

ej2-javascript/chart/internationalization.md
Hi @MallikaRK
Worked on page with redirect for js grid.
Regards,
Sharly A.
=> SEO-179773-JS-Charts-docs

ej2-javascript/circular-chart-3d/ej2-javascript-circular-chart-3d-toc.html, ej2-javascript/circular-chart-3d/ej2-typescript-circular-chart-3d-toc.html, ej2-javascript/circular-chart-3d/js/es5-getting-started.md, ej2-javascript/circular-chart-3d/ts/getting-started.md, ej2-javascript/code-snippet/circular-chart/getting-started/index.css, ej2-javascript/code-snippet/circular-chart/getting-started/index.js, ej2-javascript/code-snippet/circular-chart/getting-started/index.ts, ej2-javascript/code-snippet/circular-chart/getting-started/js/index.html, ej2-javascript/code-snippet/circular-chart/getting-started/systemjs.config.js, ej2-javascript/code-snippet/circular-chart/getting-started/ts/index.html
Added circular chart 3d samples.
=> 871723: Added circular chart 3d sample in TypeScript and JavaScript.

ej2-javascript/circular-chart-3d/circular-chart-print.md, ej2-javascript/circular-chart-3d/data-label.md, ej2-javascript/circular-chart-3d/ej2-javascript-circular-chart-3d-toc.html, ej2-javascript/circular-chart-3d/ej2-typescript-circular-chart-3d-toc.html, ej2-javascript/circular-chart-3d/empty-points.md, ej2-javascript/circular-chart-3d/legend.md, ej2-javascript/circular-chart-3d/pie-dough-nut.md, ej2-javascript/circular-chart-3d/title-and-sub-title.md, ej2-javascript/circular-chart-3d/tool-tip.md
Added description corrections in circular chart 3d features samples.
=> 871723: Added description corrections circular chart 3d features sample in TypeScript and JavaScript UG.

ej2-javascript/circular-chart-3d/js/es5-getting-started.md, ej2-javascript/circular-chart-3d/ts/getting-started.md
Added description corrections in circular chart 3d features samples.
=> 871723: Added corrections in circular chart 3d features sample in TypeScript and JavaScript UG.

ej2-javascript/circular-chart-3d/data-label.md, ej2-javascript/circular-chart-3d/ej2-javascript-circular-chart-3d-toc.html, ej2-javascript/circular-chart-3d/ej2-typescript-circular-chart-3d-toc.html, ej2-javascript/circular-chart-3d/empty-points.md, ej2-javascript/circular-chart-3d/legend.md, ej2-javascript/circular-chart-3d/pie-donut-chart.md, ej2-javascript/circular-chart-3d/print-and-export.md, ej2-javascript/circular-chart-3d/title-and-subtitle.md, ej2-javascript/circular-chart-3d/tooltip.md
Added circular chart 3d features samples.
=> 871723: Added description changes in circular chart 3d in TypeScript and JavaScript UG.

ej2-javascript/circular-chart-3d/data-label.md, ej2-javascript/circular-chart-3d/ej2-javascript-circular-chart-3d-toc.html, ej2-javascript/circular-chart-3d/ej2-typescript-circular-chart-3d-toc.html, ej2-javascript/circular-chart-3d/empty-points.md, ej2-javascript/circular-chart-3d/legend.md, ej2-javascript/circular-chart-3d/pie-donut-chart.md, ej2-javascript/circular-chart-3d/print-and-export.md, ej2-javascript/circular-chart-3d/title-and-subtitle.md, ej2-javascript/circular-chart-3d/tooltip.md
Added circular chart 3d features samples.
=> 875329: Added description changes in circular chart 3d in TypeScript and JavaScript UG.

ej2-javascript/code-snippet/circular-chart/user-interaction/export/index.js, ej2-javascript/code-snippet/circular-chart/user-interaction/export/index.ts
Resolved preview issues in circular chart 3d features samples.
=> 871723: Resolved preview issues in circular chart 3d in TypeScript and JavaScript UG.

ej2-javascript/code-snippet/circular-chart/user-interaction/export/index.js, ej2-javascript/code-snippet/circular-chart/user-interaction/export/index.ts
Resolved preview issues in circular chart 3d features samples.
=> 875329: Resolved preview issues in circular chart 3d in TypeScript and JavaScript UG.
